export const ActionTypes = {
  GET_CRYPTOCURRENCY_LIST: "GET_CRYPTOCURRENCY_LIST",
  GET_GLOBAL_CRYPTOCURRENCY_DATA: "GET_GLOBAL_CRYPTOCURRENCY_DATA",
  GET_EXCHANGES: "GET_EXCHANGES",
  SET_CURRENT_COIN: "SET_CURRENT_COIN",
};
